import paramiko


# Found in AWS Transfer Family endpoint details section
ENDPOINT = 'ENDPOINT'
# Create it by adding user AWS Transfer Family
USERNAME = 'USERNAME'
# This is generated by Linux ssh-keygen
PRIVATE_KEY = 'PATH_TO_PRIVATE_KEY_FILE'
FILE = 'PATH_TO_FILE'


def main():

    # Make SFTP client
    client = paramiko.SSHClient()
    client.set_missing_host_key_policy(paramiko.AutoAddPolicy())

    # Login SFTP
    key = paramiko.RSAKey.from_private_key_file(PRIVATE_KEY)
    client.connect(
        ENDPOINT,
        username=USERNAME,
        pkey=key
    )
    sftp = client.open_sftp()

    # ls
    print(sftp.listdir())

    # cd up one level
    sftp.chdir('..')
    print(sftp.listdir())

    # Upload file
    sftp.put(localpath=FILE, remotepath=FILE)

    # Close connection
    sftp.close()
    client.close()


if __name__ == '__main__':
    main()
